version: '3'
services:

    ui:
        container_name: globomap_ui
        build:
            context: ./
            dockerfile: scripts/docker/Dockerfile
        ports:
            - "${GMAP_UI_PORT}:8888"
        env_file:
            - scripts/docker/globomap_ui.env
        volumes:
            - .:/app
            - ./scripts/docker/ca-certificates.crt:/usr/src/app/server/ca-certificates.crt:ro
        command: node server
        networks:
            - globomap-api_globomap_net
        external_links:
            - globomap_api:globomap_api
            - globomap_redis:globomap_redis

networks:
    globomap-api_globomap_net:
        external: true